export { default as Landing } from './landing'
export { default as Auth } from './auth'
export { default as Dashboard } from './dashboard'
export { default as Pricing } from './pricing'
export { default as Demo } from './demo'
